[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Usd"
version = "1.0.0"
description = "Full Pixar USD build with Python, UsdImaging, Hydra, and plugins"
authors = [{ name = "Pixel Muratori" }]
license-files = ["usd_package/LICENSE.txt", "usd_package/NOTICE.txt"]
requires-python = ">=3.10"
readme = "usd_package/README.md"
dependencies = [
    "jinja2",
    "PyOpenGL"
]

[tool.setuptools.packages.find]
where = ["usd_build/lib/python"]
include = ["pxr*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"pxr" = ["**/*.**"] # install everything found in usd_package. it is already well formed and prepared


[tool.setuptools.data-files]
"Lib/site_packages/pxr" = [
    "usd_build/lib/*.dll",
    "usd_build/bin/*.dll"
]
"Scripts" = [
    "usd_build/Scripts/*"
]